// Code generated by github.com/tinylib/msgp DO NOT EDIT.

package webauthn

import (
	"github.com/go-webauthn/webauthn/protocol"
	"github.com/tinylib/msgp/msgp"
)

// DecodeMsg implements msgp.Decodable
func (z *Authenticator) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "aaguid":
			z.AAGUID, err = dc.ReadBytes(z.AAGUID)
			if err != nil {
				err = msgp.WrapError(err, "AAGUID")
				return
			}
		case "sc":
			z.SignCount, err = dc.ReadUint32()
			if err != nil {
				err = msgp.WrapError(err, "SignCount")
				return
			}
		case "cw":
			z.CloneWarning, err = dc.ReadBool()
			if err != nil {
				err = msgp.WrapError(err, "CloneWarning")
				return
			}
		case "aa":
			{
				var zb0002 string
				zb0002, err = dc.ReadString()
				if err != nil {
					err = msgp.WrapError(err, "Attachment")
					return
				}
				z.Attachment = protocol.AuthenticatorAttachment(zb0002)
			}
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z *Authenticator) EncodeMsg(en *msgp.Writer) (err error) {
	// map header, size 4
	// write "aaguid"
	err = en.Append(0x84, 0xa6, 0x61, 0x61, 0x67, 0x75, 0x69, 0x64)
	if err != nil {
		return
	}
	err = en.WriteBytes(z.AAGUID)
	if err != nil {
		err = msgp.WrapError(err, "AAGUID")
		return
	}
	// write "sc"
	err = en.Append(0xa2, 0x73, 0x63)
	if err != nil {
		return
	}
	err = en.WriteUint32(z.SignCount)
	if err != nil {
		err = msgp.WrapError(err, "SignCount")
		return
	}
	// write "cw"
	err = en.Append(0xa2, 0x63, 0x77)
	if err != nil {
		return
	}
	err = en.WriteBool(z.CloneWarning)
	if err != nil {
		err = msgp.WrapError(err, "CloneWarning")
		return
	}
	// write "aa"
	err = en.Append(0xa2, 0x61, 0x61)
	if err != nil {
		return
	}
	err = en.WriteString(string(z.Attachment))
	if err != nil {
		err = msgp.WrapError(err, "Attachment")
		return
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z *Authenticator) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// map header, size 4
	// string "aaguid"
	o = append(o, 0x84, 0xa6, 0x61, 0x61, 0x67, 0x75, 0x69, 0x64)
	o = msgp.AppendBytes(o, z.AAGUID)
	// string "sc"
	o = append(o, 0xa2, 0x73, 0x63)
	o = msgp.AppendUint32(o, z.SignCount)
	// string "cw"
	o = append(o, 0xa2, 0x63, 0x77)
	o = msgp.AppendBool(o, z.CloneWarning)
	// string "aa"
	o = append(o, 0xa2, 0x61, 0x61)
	o = msgp.AppendString(o, string(z.Attachment))
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *Authenticator) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "aaguid":
			z.AAGUID, bts, err = msgp.ReadBytesBytes(bts, z.AAGUID)
			if err != nil {
				err = msgp.WrapError(err, "AAGUID")
				return
			}
		case "sc":
			z.SignCount, bts, err = msgp.ReadUint32Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "SignCount")
				return
			}
		case "cw":
			z.CloneWarning, bts, err = msgp.ReadBoolBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "CloneWarning")
				return
			}
		case "aa":
			{
				var zb0002 string
				zb0002, bts, err = msgp.ReadStringBytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "Attachment")
					return
				}
				z.Attachment = protocol.AuthenticatorAttachment(zb0002)
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *Authenticator) Msgsize() (s int) {
	s = 1 + 7 + msgp.BytesPrefixSize + len(z.AAGUID) + 3 + msgp.Uint32Size + 3 + msgp.BoolSize + 3 + msgp.StringPrefixSize + len(string(z.Attachment))
	return
}
