// Code generated by github.com/tinylib/msgp DO NOT EDIT.

package webauthn

import (
	"github.com/go-webauthn/webauthn/protocol"
	"github.com/tinylib/msgp/msgp"
)

// DecodeMsg implements msgp.Decodable
func (z *SessionData) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	var zb0001Mask uint8 /* 7 bits */
	_ = zb0001Mask
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "c":
			z.Challenge, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "Challenge")
				return
			}
		case "r":
			z.RelyingPartyID, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "RelyingPartyID")
				return
			}
			zb0001Mask |= 0x1
		case "o":
			z.Origin, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "Origin")
				return
			}
			zb0001Mask |= 0x2
		case "u":
			z.UserID, err = dc.ReadBytes(z.UserID)
			if err != nil {
				err = msgp.WrapError(err, "UserID")
				return
			}
			zb0001Mask |= 0x4
		case "allow":
			var zb0002 uint32
			zb0002, err = dc.ReadArrayHeader()
			if err != nil {
				err = msgp.WrapError(err, "AllowedCredentialIDs")
				return
			}
			if cap(z.AllowedCredentialIDs) >= int(zb0002) {
				z.AllowedCredentialIDs = (z.AllowedCredentialIDs)[:zb0002]
			} else {
				z.AllowedCredentialIDs = make([][]byte, zb0002)
			}
			for za0001 := range z.AllowedCredentialIDs {
				z.AllowedCredentialIDs[za0001], err = dc.ReadBytes(z.AllowedCredentialIDs[za0001])
				if err != nil {
					err = msgp.WrapError(err, "AllowedCredentialIDs", za0001)
					return
				}
			}
			zb0001Mask |= 0x8
		case "exp":
			z.Expires, err = dc.ReadTime()
			if err != nil {
				err = msgp.WrapError(err, "Expires")
				return
			}
		case "uv":
			{
				var zb0003 string
				zb0003, err = dc.ReadString()
				if err != nil {
					err = msgp.WrapError(err, "UserVerification")
					return
				}
				z.UserVerification = protocol.UserVerificationRequirement(zb0003)
			}
			zb0001Mask |= 0x10
		case "exts":
			err = (*sessionExtensions)(&z.Extensions).DecodeMsg(dc)
			if err != nil {
				err = msgp.WrapError(err, "Extensions")
				return
			}
		case "params":
			var zb0004 uint32
			zb0004, err = dc.ReadArrayHeader()
			if err != nil {
				err = msgp.WrapError(err, "CredParams")
				return
			}
			if cap(z.CredParams) >= int(zb0004) {
				z.CredParams = (z.CredParams)[:zb0004]
			} else {
				z.CredParams = make([]protocol.CredentialParameter, zb0004)
			}
			for za0002 := range z.CredParams {
				err = z.CredParams[za0002].DecodeMsg(dc)
				if err != nil {
					err = msgp.WrapError(err, "CredParams", za0002)
					return
				}
			}
			zb0001Mask |= 0x20
		case "cmr":
			{
				var zb0005 string
				zb0005, err = dc.ReadString()
				if err != nil {
					err = msgp.WrapError(err, "Mediation")
					return
				}
				z.Mediation = protocol.CredentialMediationRequirement(zb0005)
			}
			zb0001Mask |= 0x40
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	// Clear omitted fields.
	if zb0001Mask != 0x7f {
		if (zb0001Mask & 0x1) == 0 {
			z.RelyingPartyID = ""
		}
		if (zb0001Mask & 0x2) == 0 {
			z.Origin = ""
		}
		if (zb0001Mask & 0x4) == 0 {
			z.UserID = nil
		}
		if (zb0001Mask & 0x8) == 0 {
			z.AllowedCredentialIDs = nil
		}
		if (zb0001Mask & 0x10) == 0 {
			z.UserVerification = ""
		}
		if (zb0001Mask & 0x20) == 0 {
			z.CredParams = nil
		}
		if (zb0001Mask & 0x40) == 0 {
			z.Mediation = ""
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z *SessionData) EncodeMsg(en *msgp.Writer) (err error) {
	// check for omitted fields
	zb0001Len := uint32(10)
	var zb0001Mask uint16 /* 10 bits */
	_ = zb0001Mask
	if z.RelyingPartyID == "" {
		zb0001Len--
		zb0001Mask |= 0x2
	}
	if z.Origin == "" {
		zb0001Len--
		zb0001Mask |= 0x4
	}
	if z.UserID == nil {
		zb0001Len--
		zb0001Mask |= 0x8
	}
	if z.AllowedCredentialIDs == nil {
		zb0001Len--
		zb0001Mask |= 0x10
	}
	if z.UserVerification == "" {
		zb0001Len--
		zb0001Mask |= 0x40
	}
	if z.CredParams == nil {
		zb0001Len--
		zb0001Mask |= 0x100
	}
	if z.Mediation == "" {
		zb0001Len--
		zb0001Mask |= 0x200
	}
	// variable map header, size zb0001Len
	err = en.Append(0x80 | uint8(zb0001Len))
	if err != nil {
		return
	}

	// skip if no fields are to be emitted
	if zb0001Len != 0 {
		// write "c"
		err = en.Append(0xa1, 0x63)
		if err != nil {
			return
		}
		err = en.WriteString(z.Challenge)
		if err != nil {
			err = msgp.WrapError(err, "Challenge")
			return
		}
		if (zb0001Mask & 0x2) == 0 { // if not omitted
			// write "r"
			err = en.Append(0xa1, 0x72)
			if err != nil {
				return
			}
			err = en.WriteString(z.RelyingPartyID)
			if err != nil {
				err = msgp.WrapError(err, "RelyingPartyID")
				return
			}
		}
		if (zb0001Mask & 0x4) == 0 { // if not omitted
			// write "o"
			err = en.Append(0xa1, 0x6f)
			if err != nil {
				return
			}
			err = en.WriteString(z.Origin)
			if err != nil {
				err = msgp.WrapError(err, "Origin")
				return
			}
		}
		if (zb0001Mask & 0x8) == 0 { // if not omitted
			// write "u"
			err = en.Append(0xa1, 0x75)
			if err != nil {
				return
			}
			err = en.WriteBytes(z.UserID)
			if err != nil {
				err = msgp.WrapError(err, "UserID")
				return
			}
		}
		if (zb0001Mask & 0x10) == 0 { // if not omitted
			// write "allow"
			err = en.Append(0xa5, 0x61, 0x6c, 0x6c, 0x6f, 0x77)
			if err != nil {
				return
			}
			err = en.WriteArrayHeader(uint32(len(z.AllowedCredentialIDs)))
			if err != nil {
				err = msgp.WrapError(err, "AllowedCredentialIDs")
				return
			}
			for za0001 := range z.AllowedCredentialIDs {
				err = en.WriteBytes(z.AllowedCredentialIDs[za0001])
				if err != nil {
					err = msgp.WrapError(err, "AllowedCredentialIDs", za0001)
					return
				}
			}
		}
		// write "exp"
		err = en.Append(0xa3, 0x65, 0x78, 0x70)
		if err != nil {
			return
		}
		err = en.WriteTime(z.Expires)
		if err != nil {
			err = msgp.WrapError(err, "Expires")
			return
		}
		if (zb0001Mask & 0x40) == 0 { // if not omitted
			// write "uv"
			err = en.Append(0xa2, 0x75, 0x76)
			if err != nil {
				return
			}
			err = en.WriteString(string(z.UserVerification))
			if err != nil {
				err = msgp.WrapError(err, "UserVerification")
				return
			}
		}
		// write "exts"
		err = en.Append(0xa4, 0x65, 0x78, 0x74, 0x73)
		if err != nil {
			return
		}
		err = (*sessionExtensions)(&z.Extensions).EncodeMsg(en)
		if err != nil {
			err = msgp.WrapError(err, "Extensions")
			return
		}
		if (zb0001Mask & 0x100) == 0 { // if not omitted
			// write "params"
			err = en.Append(0xa6, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x73)
			if err != nil {
				return
			}
			err = en.WriteArrayHeader(uint32(len(z.CredParams)))
			if err != nil {
				err = msgp.WrapError(err, "CredParams")
				return
			}
			for za0002 := range z.CredParams {
				err = z.CredParams[za0002].EncodeMsg(en)
				if err != nil {
					err = msgp.WrapError(err, "CredParams", za0002)
					return
				}
			}
		}
		if (zb0001Mask & 0x200) == 0 { // if not omitted
			// write "cmr"
			err = en.Append(0xa3, 0x63, 0x6d, 0x72)
			if err != nil {
				return
			}
			err = en.WriteString(string(z.Mediation))
			if err != nil {
				err = msgp.WrapError(err, "Mediation")
				return
			}
		}
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z *SessionData) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// check for omitted fields
	zb0001Len := uint32(10)
	var zb0001Mask uint16 /* 10 bits */
	_ = zb0001Mask
	if z.RelyingPartyID == "" {
		zb0001Len--
		zb0001Mask |= 0x2
	}
	if z.Origin == "" {
		zb0001Len--
		zb0001Mask |= 0x4
	}
	if z.UserID == nil {
		zb0001Len--
		zb0001Mask |= 0x8
	}
	if z.AllowedCredentialIDs == nil {
		zb0001Len--
		zb0001Mask |= 0x10
	}
	if z.UserVerification == "" {
		zb0001Len--
		zb0001Mask |= 0x40
	}
	if z.CredParams == nil {
		zb0001Len--
		zb0001Mask |= 0x100
	}
	if z.Mediation == "" {
		zb0001Len--
		zb0001Mask |= 0x200
	}
	// variable map header, size zb0001Len
	o = append(o, 0x80|uint8(zb0001Len))

	// skip if no fields are to be emitted
	if zb0001Len != 0 {
		// string "c"
		o = append(o, 0xa1, 0x63)
		o = msgp.AppendString(o, z.Challenge)
		if (zb0001Mask & 0x2) == 0 { // if not omitted
			// string "r"
			o = append(o, 0xa1, 0x72)
			o = msgp.AppendString(o, z.RelyingPartyID)
		}
		if (zb0001Mask & 0x4) == 0 { // if not omitted
			// string "o"
			o = append(o, 0xa1, 0x6f)
			o = msgp.AppendString(o, z.Origin)
		}
		if (zb0001Mask & 0x8) == 0 { // if not omitted
			// string "u"
			o = append(o, 0xa1, 0x75)
			o = msgp.AppendBytes(o, z.UserID)
		}
		if (zb0001Mask & 0x10) == 0 { // if not omitted
			// string "allow"
			o = append(o, 0xa5, 0x61, 0x6c, 0x6c, 0x6f, 0x77)
			o = msgp.AppendArrayHeader(o, uint32(len(z.AllowedCredentialIDs)))
			for za0001 := range z.AllowedCredentialIDs {
				o = msgp.AppendBytes(o, z.AllowedCredentialIDs[za0001])
			}
		}
		// string "exp"
		o = append(o, 0xa3, 0x65, 0x78, 0x70)
		o = msgp.AppendTime(o, z.Expires)
		if (zb0001Mask & 0x40) == 0 { // if not omitted
			// string "uv"
			o = append(o, 0xa2, 0x75, 0x76)
			o = msgp.AppendString(o, string(z.UserVerification))
		}
		// string "exts"
		o = append(o, 0xa4, 0x65, 0x78, 0x74, 0x73)
		o, err = (*sessionExtensions)(&z.Extensions).MarshalMsg(o)
		if err != nil {
			err = msgp.WrapError(err, "Extensions")
			return
		}
		if (zb0001Mask & 0x100) == 0 { // if not omitted
			// string "params"
			o = append(o, 0xa6, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x73)
			o = msgp.AppendArrayHeader(o, uint32(len(z.CredParams)))
			for za0002 := range z.CredParams {
				o, err = z.CredParams[za0002].MarshalMsg(o)
				if err != nil {
					err = msgp.WrapError(err, "CredParams", za0002)
					return
				}
			}
		}
		if (zb0001Mask & 0x200) == 0 { // if not omitted
			// string "cmr"
			o = append(o, 0xa3, 0x63, 0x6d, 0x72)
			o = msgp.AppendString(o, string(z.Mediation))
		}
	}
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *SessionData) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	var zb0001Mask uint8 /* 7 bits */
	_ = zb0001Mask
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "c":
			z.Challenge, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Challenge")
				return
			}
		case "r":
			z.RelyingPartyID, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "RelyingPartyID")
				return
			}
			zb0001Mask |= 0x1
		case "o":
			z.Origin, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Origin")
				return
			}
			zb0001Mask |= 0x2
		case "u":
			z.UserID, bts, err = msgp.ReadBytesBytes(bts, z.UserID)
			if err != nil {
				err = msgp.WrapError(err, "UserID")
				return
			}
			zb0001Mask |= 0x4
		case "allow":
			var zb0002 uint32
			zb0002, bts, err = msgp.ReadArrayHeaderBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "AllowedCredentialIDs")
				return
			}
			if cap(z.AllowedCredentialIDs) >= int(zb0002) {
				z.AllowedCredentialIDs = (z.AllowedCredentialIDs)[:zb0002]
			} else {
				z.AllowedCredentialIDs = make([][]byte, zb0002)
			}
			for za0001 := range z.AllowedCredentialIDs {
				z.AllowedCredentialIDs[za0001], bts, err = msgp.ReadBytesBytes(bts, z.AllowedCredentialIDs[za0001])
				if err != nil {
					err = msgp.WrapError(err, "AllowedCredentialIDs", za0001)
					return
				}
			}
			zb0001Mask |= 0x8
		case "exp":
			z.Expires, bts, err = msgp.ReadTimeBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Expires")
				return
			}
		case "uv":
			{
				var zb0003 string
				zb0003, bts, err = msgp.ReadStringBytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "UserVerification")
					return
				}
				z.UserVerification = protocol.UserVerificationRequirement(zb0003)
			}
			zb0001Mask |= 0x10
		case "exts":
			bts, err = (*sessionExtensions)(&z.Extensions).UnmarshalMsg(bts)
			if err != nil {
				err = msgp.WrapError(err, "Extensions")
				return
			}
		case "params":
			var zb0004 uint32
			zb0004, bts, err = msgp.ReadArrayHeaderBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "CredParams")
				return
			}
			if cap(z.CredParams) >= int(zb0004) {
				z.CredParams = (z.CredParams)[:zb0004]
			} else {
				z.CredParams = make([]protocol.CredentialParameter, zb0004)
			}
			for za0002 := range z.CredParams {
				bts, err = z.CredParams[za0002].UnmarshalMsg(bts)
				if err != nil {
					err = msgp.WrapError(err, "CredParams", za0002)
					return
				}
			}
			zb0001Mask |= 0x20
		case "cmr":
			{
				var zb0005 string
				zb0005, bts, err = msgp.ReadStringBytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "Mediation")
					return
				}
				z.Mediation = protocol.CredentialMediationRequirement(zb0005)
			}
			zb0001Mask |= 0x40
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	// Clear omitted fields.
	if zb0001Mask != 0x7f {
		if (zb0001Mask & 0x1) == 0 {
			z.RelyingPartyID = ""
		}
		if (zb0001Mask & 0x2) == 0 {
			z.Origin = ""
		}
		if (zb0001Mask & 0x4) == 0 {
			z.UserID = nil
		}
		if (zb0001Mask & 0x8) == 0 {
			z.AllowedCredentialIDs = nil
		}
		if (zb0001Mask & 0x10) == 0 {
			z.UserVerification = ""
		}
		if (zb0001Mask & 0x20) == 0 {
			z.CredParams = nil
		}
		if (zb0001Mask & 0x40) == 0 {
			z.Mediation = ""
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *SessionData) Msgsize() (s int) {
	s = 1 + 2 + msgp.StringPrefixSize + len(z.Challenge) + 2 + msgp.StringPrefixSize + len(z.RelyingPartyID) + 2 + msgp.StringPrefixSize + len(z.Origin) + 2 + msgp.BytesPrefixSize + len(z.UserID) + 6 + msgp.ArrayHeaderSize
	for za0001 := range z.AllowedCredentialIDs {
		s += msgp.BytesPrefixSize + len(z.AllowedCredentialIDs[za0001])
	}
	s += 4 + msgp.TimeSize + 3 + msgp.StringPrefixSize + len(string(z.UserVerification)) + 5 + (*sessionExtensions)(&z.Extensions).Msgsize() + 7 + msgp.ArrayHeaderSize
	for za0002 := range z.CredParams {
		s += z.CredParams[za0002].Msgsize()
	}
	s += 4 + msgp.StringPrefixSize + len(string(z.Mediation))
	return
}

// DecodeMsg implements msgp.Decodable
func (z *sessionExtensions) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	var zb0001Mask uint16 /* 10 bits */
	_ = zb0001Mask
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "req":
			var zb0002 uint32
			zb0002, err = dc.ReadArrayHeader()
			if err != nil {
				err = msgp.WrapError(err, "Requested")
				return
			}
			if cap(z.Requested) >= int(zb0002) {
				z.Requested = (z.Requested)[:zb0002]
			} else {
				z.Requested = make([]string, zb0002)
			}
			for za0001 := range z.Requested {
				z.Requested[za0001], err = dc.ReadString()
				if err != nil {
					err = msgp.WrapError(err, "Requested", za0001)
					return
				}
			}
			zb0001Mask |= 0x1
		case "appid":
			z.AppID, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "AppID")
				return
			}
			zb0001Mask |= 0x2
		case "appidExclude":
			z.AppIDExclude, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "AppIDExclude")
				return
			}
			zb0001Mask |= 0x4
		case "largeBlob":
			{
				var zb0003 string
				zb0003, err = dc.ReadString()
				if err != nil {
					err = msgp.WrapError(err, "LargeBlob")
					return
				}
				z.LargeBlob = protocol.LargeBlobSupport(zb0003)
			}
			zb0001Mask |= 0x8
		case "lbRead":
			z.LargeBlobRead, err = dc.ReadBool()
			if err != nil {
				err = msgp.WrapError(err, "LargeBlobRead")
				return
			}
			zb0001Mask |= 0x10
		case "lbWrite":
			z.LargeBlobWrite, err = dc.ReadBool()
			if err != nil {
				err = msgp.WrapError(err, "LargeBlobWrite")
				return
			}
			zb0001Mask |= 0x20
		case "credProtect":
			{
				var zb0004 string
				zb0004, err = dc.ReadString()
				if err != nil {
					err = msgp.WrapError(err, "CredentialProtectionPolicy")
					return
				}
				z.CredentialProtectionPolicy = protocol.CredentialProtectionPolicy(zb0004)
			}
			zb0001Mask |= 0x40
		case "cpEnforce":
			z.EnforceCredentialProtectionPolicy, err = dc.ReadBool()
			if err != nil {
				err = msgp.WrapError(err, "EnforceCredentialProtectionPolicy")
				return
			}
			zb0001Mask |= 0x80
		case "credBlob":
			z.CredBlob, err = dc.ReadBool()
			if err != nil {
				err = msgp.WrapError(err, "CredBlob")
				return
			}
			zb0001Mask |= 0x100
		case "extra":
			var zb0005 uint32
			zb0005, err = dc.ReadMapHeader()
			if err != nil {
				err = msgp.WrapError(err, "Extra")
				return
			}
			if z.Extra == nil {
				z.Extra = make(map[string]interface{}, zb0005)
			} else if len(z.Extra) > 0 {
				clear(z.Extra)
			}
			for zb0005 > 0 {
				zb0005--
				var za0002 string
				za0002, err = dc.ReadString()
				if err != nil {
					err = msgp.WrapError(err, "Extra")
					return
				}
				var za0003 interface{}
				za0003, err = dc.ReadIntf()
				if err != nil {
					err = msgp.WrapError(err, "Extra", za0002)
					return
				}
				z.Extra[za0002] = za0003
			}
			zb0001Mask |= 0x200
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	// Clear omitted fields.
	if zb0001Mask != 0x3ff {
		if (zb0001Mask & 0x1) == 0 {
			z.Requested = nil
		}
		if (zb0001Mask & 0x2) == 0 {
			z.AppID = ""
		}
		if (zb0001Mask & 0x4) == 0 {
			z.AppIDExclude = ""
		}
		if (zb0001Mask & 0x8) == 0 {
			z.LargeBlob = ""
		}
		if (zb0001Mask & 0x10) == 0 {
			z.LargeBlobRead = false
		}
		if (zb0001Mask & 0x20) == 0 {
			z.LargeBlobWrite = false
		}
		if (zb0001Mask & 0x40) == 0 {
			z.CredentialProtectionPolicy = ""
		}
		if (zb0001Mask & 0x80) == 0 {
			z.EnforceCredentialProtectionPolicy = false
		}
		if (zb0001Mask & 0x100) == 0 {
			z.CredBlob = false
		}
		if (zb0001Mask & 0x200) == 0 {
			z.Extra = nil
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z *sessionExtensions) EncodeMsg(en *msgp.Writer) (err error) {
	// check for omitted fields
	zb0001Len := uint32(10)
	var zb0001Mask uint16 /* 10 bits */
	_ = zb0001Mask
	if z.Requested == nil {
		zb0001Len--
		zb0001Mask |= 0x1
	}
	if z.AppID == "" {
		zb0001Len--
		zb0001Mask |= 0x2
	}
	if z.AppIDExclude == "" {
		zb0001Len--
		zb0001Mask |= 0x4
	}
	if z.LargeBlob == "" {
		zb0001Len--
		zb0001Mask |= 0x8
	}
	if z.LargeBlobRead == false {
		zb0001Len--
		zb0001Mask |= 0x10
	}
	if z.LargeBlobWrite == false {
		zb0001Len--
		zb0001Mask |= 0x20
	}
	if z.CredentialProtectionPolicy == "" {
		zb0001Len--
		zb0001Mask |= 0x40
	}
	if z.EnforceCredentialProtectionPolicy == false {
		zb0001Len--
		zb0001Mask |= 0x80
	}
	if z.CredBlob == false {
		zb0001Len--
		zb0001Mask |= 0x100
	}
	if z.Extra == nil {
		zb0001Len--
		zb0001Mask |= 0x200
	}
	// variable map header, size zb0001Len
	err = en.Append(0x80 | uint8(zb0001Len))
	if err != nil {
		return
	}

	// skip if no fields are to be emitted
	if zb0001Len != 0 {
		if (zb0001Mask & 0x1) == 0 { // if not omitted
			// write "req"
			err = en.Append(0xa3, 0x72, 0x65, 0x71)
			if err != nil {
				return
			}
			err = en.WriteArrayHeader(uint32(len(z.Requested)))
			if err != nil {
				err = msgp.WrapError(err, "Requested")
				return
			}
			for za0001 := range z.Requested {
				err = en.WriteString(z.Requested[za0001])
				if err != nil {
					err = msgp.WrapError(err, "Requested", za0001)
					return
				}
			}
		}
		if (zb0001Mask & 0x2) == 0 { // if not omitted
			// write "appid"
			err = en.Append(0xa5, 0x61, 0x70, 0x70, 0x69, 0x64)
			if err != nil {
				return
			}
			err = en.WriteString(z.AppID)
			if err != nil {
				err = msgp.WrapError(err, "AppID")
				return
			}
		}
		if (zb0001Mask & 0x4) == 0 { // if not omitted
			// write "appidExclude"
			err = en.Append(0xac, 0x61, 0x70, 0x70, 0x69, 0x64, 0x45, 0x78, 0x63, 0x6c, 0x75, 0x64, 0x65)
			if err != nil {
				return
			}
			err = en.WriteString(z.AppIDExclude)
			if err != nil {
				err = msgp.WrapError(err, "AppIDExclude")
				return
			}
		}
		if (zb0001Mask & 0x8) == 0 { // if not omitted
			// write "largeBlob"
			err = en.Append(0xa9, 0x6c, 0x61, 0x72, 0x67, 0x65, 0x42, 0x6c, 0x6f, 0x62)
			if err != nil {
				return
			}
			err = en.WriteString(string(z.LargeBlob))
			if err != nil {
				err = msgp.WrapError(err, "LargeBlob")
				return
			}
		}
		if (zb0001Mask & 0x10) == 0 { // if not omitted
			// write "lbRead"
			err = en.Append(0xa6, 0x6c, 0x62, 0x52, 0x65, 0x61, 0x64)
			if err != nil {
				return
			}
			err = en.WriteBool(z.LargeBlobRead)
			if err != nil {
				err = msgp.WrapError(err, "LargeBlobRead")
				return
			}
		}
		if (zb0001Mask & 0x20) == 0 { // if not omitted
			// write "lbWrite"
			err = en.Append(0xa7, 0x6c, 0x62, 0x57, 0x72, 0x69, 0x74, 0x65)
			if err != nil {
				return
			}
			err = en.WriteBool(z.LargeBlobWrite)
			if err != nil {
				err = msgp.WrapError(err, "LargeBlobWrite")
				return
			}
		}
		if (zb0001Mask & 0x40) == 0 { // if not omitted
			// write "credProtect"
			err = en.Append(0xab, 0x63, 0x72, 0x65, 0x64, 0x50, 0x72, 0x6f, 0x74, 0x65, 0x63, 0x74)
			if err != nil {
				return
			}
			err = en.WriteString(string(z.CredentialProtectionPolicy))
			if err != nil {
				err = msgp.WrapError(err, "CredentialProtectionPolicy")
				return
			}
		}
		if (zb0001Mask & 0x80) == 0 { // if not omitted
			// write "cpEnforce"
			err = en.Append(0xa9, 0x63, 0x70, 0x45, 0x6e, 0x66, 0x6f, 0x72, 0x63, 0x65)
			if err != nil {
				return
			}
			err = en.WriteBool(z.EnforceCredentialProtectionPolicy)
			if err != nil {
				err = msgp.WrapError(err, "EnforceCredentialProtectionPolicy")
				return
			}
		}
		if (zb0001Mask & 0x100) == 0 { // if not omitted
			// write "credBlob"
			err = en.Append(0xa8, 0x63, 0x72, 0x65, 0x64, 0x42, 0x6c, 0x6f, 0x62)
			if err != nil {
				return
			}
			err = en.WriteBool(z.CredBlob)
			if err != nil {
				err = msgp.WrapError(err, "CredBlob")
				return
			}
		}
		if (zb0001Mask & 0x200) == 0 { // if not omitted
			// write "extra"
			err = en.Append(0xa5, 0x65, 0x78, 0x74, 0x72, 0x61)
			if err != nil {
				return
			}
			err = en.WriteMapHeader(uint32(len(z.Extra)))
			if err != nil {
				err = msgp.WrapError(err, "Extra")
				return
			}
			for za0002, za0003 := range z.Extra {
				err = en.WriteString(za0002)
				if err != nil {
					err = msgp.WrapError(err, "Extra")
					return
				}
				err = en.WriteIntf(za0003)
				if err != nil {
					err = msgp.WrapError(err, "Extra", za0002)
					return
				}
			}
		}
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z *sessionExtensions) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// check for omitted fields
	zb0001Len := uint32(10)
	var zb0001Mask uint16 /* 10 bits */
	_ = zb0001Mask
	if z.Requested == nil {
		zb0001Len--
		zb0001Mask |= 0x1
	}
	if z.AppID == "" {
		zb0001Len--
		zb0001Mask |= 0x2
	}
	if z.AppIDExclude == "" {
		zb0001Len--
		zb0001Mask |= 0x4
	}
	if z.LargeBlob == "" {
		zb0001Len--
		zb0001Mask |= 0x8
	}
	if z.LargeBlobRead == false {
		zb0001Len--
		zb0001Mask |= 0x10
	}
	if z.LargeBlobWrite == false {
		zb0001Len--
		zb0001Mask |= 0x20
	}
	if z.CredentialProtectionPolicy == "" {
		zb0001Len--
		zb0001Mask |= 0x40
	}
	if z.EnforceCredentialProtectionPolicy == false {
		zb0001Len--
		zb0001Mask |= 0x80
	}
	if z.CredBlob == false {
		zb0001Len--
		zb0001Mask |= 0x100
	}
	if z.Extra == nil {
		zb0001Len--
		zb0001Mask |= 0x200
	}
	// variable map header, size zb0001Len
	o = append(o, 0x80|uint8(zb0001Len))

	// skip if no fields are to be emitted
	if zb0001Len != 0 {
		if (zb0001Mask & 0x1) == 0 { // if not omitted
			// string "req"
			o = append(o, 0xa3, 0x72, 0x65, 0x71)
			o = msgp.AppendArrayHeader(o, uint32(len(z.Requested)))
			for za0001 := range z.Requested {
				o = msgp.AppendString(o, z.Requested[za0001])
			}
		}
		if (zb0001Mask & 0x2) == 0 { // if not omitted
			// string "appid"
			o = append(o, 0xa5, 0x61, 0x70, 0x70, 0x69, 0x64)
			o = msgp.AppendString(o, z.AppID)
		}
		if (zb0001Mask & 0x4) == 0 { // if not omitted
			// string "appidExclude"
			o = append(o, 0xac, 0x61, 0x70, 0x70, 0x69, 0x64, 0x45, 0x78, 0x63, 0x6c, 0x75, 0x64, 0x65)
			o = msgp.AppendString(o, z.AppIDExclude)
		}
		if (zb0001Mask & 0x8) == 0 { // if not omitted
			// string "largeBlob"
			o = append(o, 0xa9, 0x6c, 0x61, 0x72, 0x67, 0x65, 0x42, 0x6c, 0x6f, 0x62)
			o = msgp.AppendString(o, string(z.LargeBlob))
		}
		if (zb0001Mask & 0x10) == 0 { // if not omitted
			// string "lbRead"
			o = append(o, 0xa6, 0x6c, 0x62, 0x52, 0x65, 0x61, 0x64)
			o = msgp.AppendBool(o, z.LargeBlobRead)
		}
		if (zb0001Mask & 0x20) == 0 { // if not omitted
			// string "lbWrite"
			o = append(o, 0xa7, 0x6c, 0x62, 0x57, 0x72, 0x69, 0x74, 0x65)
			o = msgp.AppendBool(o, z.LargeBlobWrite)
		}
		if (zb0001Mask & 0x40) == 0 { // if not omitted
			// string "credProtect"
			o = append(o, 0xab, 0x63, 0x72, 0x65, 0x64, 0x50, 0x72, 0x6f, 0x74, 0x65, 0x63, 0x74)
			o = msgp.AppendString(o, string(z.CredentialProtectionPolicy))
		}
		if (zb0001Mask & 0x80) == 0 { // if not omitted
			// string "cpEnforce"
			o = append(o, 0xa9, 0x63, 0x70, 0x45, 0x6e, 0x66, 0x6f, 0x72, 0x63, 0x65)
			o = msgp.AppendBool(o, z.EnforceCredentialProtectionPolicy)
		}
		if (zb0001Mask & 0x100) == 0 { // if not omitted
			// string "credBlob"
			o = append(o, 0xa8, 0x63, 0x72, 0x65, 0x64, 0x42, 0x6c, 0x6f, 0x62)
			o = msgp.AppendBool(o, z.CredBlob)
		}
		if (zb0001Mask & 0x200) == 0 { // if not omitted
			// string "extra"
			o = append(o, 0xa5, 0x65, 0x78, 0x74, 0x72, 0x61)
			o = msgp.AppendMapHeader(o, uint32(len(z.Extra)))
			for za0002, za0003 := range z.Extra {
				o = msgp.AppendString(o, za0002)
				o, err = msgp.AppendIntf(o, za0003)
				if err != nil {
					err = msgp.WrapError(err, "Extra", za0002)
					return
				}
			}
		}
	}
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *sessionExtensions) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	var zb0001Mask uint16 /* 10 bits */
	_ = zb0001Mask
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "req":
			var zb0002 uint32
			zb0002, bts, err = msgp.ReadArrayHeaderBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Requested")
				return
			}
			if cap(z.Requested) >= int(zb0002) {
				z.Requested = (z.Requested)[:zb0002]
			} else {
				z.Requested = make([]string, zb0002)
			}
			for za0001 := range z.Requested {
				z.Requested[za0001], bts, err = msgp.ReadStringBytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "Requested", za0001)
					return
				}
			}
			zb0001Mask |= 0x1
		case "appid":
			z.AppID, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "AppID")
				return
			}
			zb0001Mask |= 0x2
		case "appidExclude":
			z.AppIDExclude, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "AppIDExclude")
				return
			}
			zb0001Mask |= 0x4
		case "largeBlob":
			{
				var zb0003 string
				zb0003, bts, err = msgp.ReadStringBytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "LargeBlob")
					return
				}
				z.LargeBlob = protocol.LargeBlobSupport(zb0003)
			}
			zb0001Mask |= 0x8
		case "lbRead":
			z.LargeBlobRead, bts, err = msgp.ReadBoolBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "LargeBlobRead")
				return
			}
			zb0001Mask |= 0x10
		case "lbWrite":
			z.LargeBlobWrite, bts, err = msgp.ReadBoolBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "LargeBlobWrite")
				return
			}
			zb0001Mask |= 0x20
		case "credProtect":
			{
				var zb0004 string
				zb0004, bts, err = msgp.ReadStringBytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "CredentialProtectionPolicy")
					return
				}
				z.CredentialProtectionPolicy = protocol.CredentialProtectionPolicy(zb0004)
			}
			zb0001Mask |= 0x40
		case "cpEnforce":
			z.EnforceCredentialProtectionPolicy, bts, err = msgp.ReadBoolBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "EnforceCredentialProtectionPolicy")
				return
			}
			zb0001Mask |= 0x80
		case "credBlob":
			z.CredBlob, bts, err = msgp.ReadBoolBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "CredBlob")
				return
			}
			zb0001Mask |= 0x100
		case "extra":
			var zb0005 uint32
			zb0005, bts, err = msgp.ReadMapHeaderBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Extra")
				return
			}
			if z.Extra == nil {
				z.Extra = make(map[string]interface{}, zb0005)
			} else if len(z.Extra) > 0 {
				clear(z.Extra)
			}
			for zb0005 > 0 {
				var za0003 interface{}
				zb0005--
				var za0002 string
				za0002, bts, err = msgp.ReadStringBytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "Extra")
					return
				}
				za0003, bts, err = msgp.ReadIntfBytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "Extra", za0002)
					return
				}
				z.Extra[za0002] = za0003
			}
			zb0001Mask |= 0x200
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	// Clear omitted fields.
	if zb0001Mask != 0x3ff {
		if (zb0001Mask & 0x1) == 0 {
			z.Requested = nil
		}
		if (zb0001Mask & 0x2) == 0 {
			z.AppID = ""
		}
		if (zb0001Mask & 0x4) == 0 {
			z.AppIDExclude = ""
		}
		if (zb0001Mask & 0x8) == 0 {
			z.LargeBlob = ""
		}
		if (zb0001Mask & 0x10) == 0 {
			z.LargeBlobRead = false
		}
		if (zb0001Mask & 0x20) == 0 {
			z.LargeBlobWrite = false
		}
		if (zb0001Mask & 0x40) == 0 {
			z.CredentialProtectionPolicy = ""
		}
		if (zb0001Mask & 0x80) == 0 {
			z.EnforceCredentialProtectionPolicy = false
		}
		if (zb0001Mask & 0x100) == 0 {
			z.CredBlob = false
		}
		if (zb0001Mask & 0x200) == 0 {
			z.Extra = nil
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *sessionExtensions) Msgsize() (s int) {
	s = 1 + 4 + msgp.ArrayHeaderSize
	for za0001 := range z.Requested {
		s += msgp.StringPrefixSize + len(z.Requested[za0001])
	}
	s += 6 + msgp.StringPrefixSize + len(z.AppID) + 13 + msgp.StringPrefixSize + len(z.AppIDExclude) + 10 + msgp.StringPrefixSize + len(string(z.LargeBlob)) + 7 + msgp.BoolSize + 8 + msgp.BoolSize + 12 + msgp.StringPrefixSize + len(string(z.CredentialProtectionPolicy)) + 10 + msgp.BoolSize + 9 + msgp.BoolSize + 6 + msgp.MapHeaderSize
	if z.Extra != nil {
		for za0002, za0003 := range z.Extra {
			_ = za0003
			s += msgp.StringPrefixSize + len(za0002) + msgp.GuessSize(za0003)
		}
	}
	return
}
