// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/go-webauthn/webauthn/metadata (interfaces: ExtendedProvider)
//
// Generated by this command:
//
//	mockgen -package mocks -destination metadata_extended.go -mock_names ExtendedProvider=MockMetadataExtendedProvider github.com/go-webauthn/webauthn/metadata ExtendedProvider
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	metadata "github.com/go-webauthn/webauthn/metadata"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockMetadataExtendedProvider is a mock of ExtendedProvider interface.
type MockMetadataExtendedProvider struct {
	ctrl     *gomock.Controller
	recorder *MockMetadataExtendedProviderMockRecorder
	isgomock struct{}
}

// MockMetadataExtendedProviderMockRecorder is the mock recorder for MockMetadataExtendedProvider.
type MockMetadataExtendedProviderMockRecorder struct {
	mock *MockMetadataExtendedProvider
}

// NewMockMetadataExtendedProvider creates a new mock instance.
func NewMockMetadataExtendedProvider(ctrl *gomock.Controller) *MockMetadataExtendedProvider {
	mock := &MockMetadataExtendedProvider{ctrl: ctrl}
	mock.recorder = &MockMetadataExtendedProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMetadataExtendedProvider) EXPECT() *MockMetadataExtendedProviderMockRecorder {
	return m.recorder
}

// GetEntry mocks base method.
func (m *MockMetadataExtendedProvider) GetEntry(ctx context.Context, aaguid uuid.UUID) (*metadata.Entry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEntry", ctx, aaguid)
	ret0, _ := ret[0].(*metadata.Entry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEntry indicates an expected call of GetEntry.
func (mr *MockMetadataExtendedProviderMockRecorder) GetEntry(ctx, aaguid any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEntry", reflect.TypeOf((*MockMetadataExtendedProvider)(nil).GetEntry), ctx, aaguid)
}

// GetEntryByKeyIdentifier mocks base method.
func (m *MockMetadataExtendedProvider) GetEntryByKeyIdentifier(ctx context.Context, keyIdentifier string) (*metadata.Entry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEntryByKeyIdentifier", ctx, keyIdentifier)
	ret0, _ := ret[0].(*metadata.Entry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEntryByKeyIdentifier indicates an expected call of GetEntryByKeyIdentifier.
func (mr *MockMetadataExtendedProviderMockRecorder) GetEntryByKeyIdentifier(ctx, keyIdentifier any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEntryByKeyIdentifier", reflect.TypeOf((*MockMetadataExtendedProvider)(nil).GetEntryByKeyIdentifier), ctx, keyIdentifier)
}

// GetValidateAAGUID mocks base method.
func (m *MockMetadataExtendedProvider) GetValidateAAGUID(ctx context.Context) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetValidateAAGUID", ctx)
	ret0, _ := ret[0].(bool)
	return ret0
}

// GetValidateAAGUID indicates an expected call of GetValidateAAGUID.
func (mr *MockMetadataExtendedProviderMockRecorder) GetValidateAAGUID(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetValidateAAGUID", reflect.TypeOf((*MockMetadataExtendedProvider)(nil).GetValidateAAGUID), ctx)
}

// GetValidateAlgorithms mocks base method.
func (m *MockMetadataExtendedProvider) GetValidateAlgorithms(ctx context.Context) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetValidateAlgorithms", ctx)
	ret0, _ := ret[0].(bool)
	return ret0
}

// GetValidateAlgorithms indicates an expected call of GetValidateAlgorithms.
func (mr *MockMetadataExtendedProviderMockRecorder) GetValidateAlgorithms(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetValidateAlgorithms", reflect.TypeOf((*MockMetadataExtendedProvider)(nil).GetValidateAlgorithms), ctx)
}

// GetValidateAttestationFormats mocks base method.
func (m *MockMetadataExtendedProvider) GetValidateAttestationFormats(ctx context.Context) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetValidateAttestationFormats", ctx)
	ret0, _ := ret[0].(bool)
	return ret0
}

// GetValidateAttestationFormats indicates an expected call of GetValidateAttestationFormats.
func (mr *MockMetadataExtendedProviderMockRecorder) GetValidateAttestationFormats(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetValidateAttestationFormats", reflect.TypeOf((*MockMetadataExtendedProvider)(nil).GetValidateAttestationFormats), ctx)
}

// GetValidateAttestationTypes mocks base method.
func (m *MockMetadataExtendedProvider) GetValidateAttestationTypes(ctx context.Context) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetValidateAttestationTypes", ctx)
	ret0, _ := ret[0].(bool)
	return ret0
}

// GetValidateAttestationTypes indicates an expected call of GetValidateAttestationTypes.
func (mr *MockMetadataExtendedProviderMockRecorder) GetValidateAttestationTypes(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetValidateAttestationTypes", reflect.TypeOf((*MockMetadataExtendedProvider)(nil).GetValidateAttestationTypes), ctx)
}

// GetValidateBackupEligibility mocks base method.
func (m *MockMetadataExtendedProvider) GetValidateBackupEligibility(ctx context.Context) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetValidateBackupEligibility", ctx)
	ret0, _ := ret[0].(bool)
	return ret0
}

// GetValidateBackupEligibility indicates an expected call of GetValidateBackupEligibility.
func (mr *MockMetadataExtendedProviderMockRecorder) GetValidateBackupEligibility(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetValidateBackupEligibility", reflect.TypeOf((*MockMetadataExtendedProvider)(nil).GetValidateBackupEligibility), ctx)
}

// GetValidateEntry mocks base method.
func (m *MockMetadataExtendedProvider) GetValidateEntry(ctx context.Context) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetValidateEntry", ctx)
	ret0, _ := ret[0].(bool)
	return ret0
}

// GetValidateEntry indicates an expected call of GetValidateEntry.
func (mr *MockMetadataExtendedProviderMockRecorder) GetValidateEntry(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetValidateEntry", reflect.TypeOf((*MockMetadataExtendedProvider)(nil).GetValidateEntry), ctx)
}

// GetValidateEntryKeyIdentifier mocks base method.
func (m *MockMetadataExtendedProvider) GetValidateEntryKeyIdentifier(ctx context.Context) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetValidateEntryKeyIdentifier", ctx)
	ret0, _ := ret[0].(bool)
	return ret0
}

// GetValidateEntryKeyIdentifier indicates an expected call of GetValidateEntryKeyIdentifier.
func (mr *MockMetadataExtendedProviderMockRecorder) GetValidateEntryKeyIdentifier(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetValidateEntryKeyIdentifier", reflect.TypeOf((*MockMetadataExtendedProvider)(nil).GetValidateEntryKeyIdentifier), ctx)
}

// GetValidateEntryPermitZeroAAGUID mocks base method.
func (m *MockMetadataExtendedProvider) GetValidateEntryPermitZeroAAGUID(ctx context.Context) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetValidateEntryPermitZeroAAGUID", ctx)
	ret0, _ := ret[0].(bool)
	return ret0
}

// GetValidateEntryPermitZeroAAGUID indicates an expected call of GetValidateEntryPermitZeroAAGUID.
func (mr *MockMetadataExtendedProviderMockRecorder) GetValidateEntryPermitZeroAAGUID(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetValidateEntryPermitZeroAAGUID", reflect.TypeOf((*MockMetadataExtendedProvider)(nil).GetValidateEntryPermitZeroAAGUID), ctx)
}

// GetValidateExtensions mocks base method.
func (m *MockMetadataExtendedProvider) GetValidateExtensions(ctx context.Context) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetValidateExtensions", ctx)
	ret0, _ := ret[0].(bool)
	return ret0
}

// GetValidateExtensions indicates an expected call of GetValidateExtensions.
func (mr *MockMetadataExtendedProviderMockRecorder) GetValidateExtensions(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetValidateExtensions", reflect.TypeOf((*MockMetadataExtendedProvider)(nil).GetValidateExtensions), ctx)
}

// GetValidateStatus mocks base method.
func (m *MockMetadataExtendedProvider) GetValidateStatus(ctx context.Context) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetValidateStatus", ctx)
	ret0, _ := ret[0].(bool)
	return ret0
}

// GetValidateStatus indicates an expected call of GetValidateStatus.
func (mr *MockMetadataExtendedProviderMockRecorder) GetValidateStatus(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetValidateStatus", reflect.TypeOf((*MockMetadataExtendedProvider)(nil).GetValidateStatus), ctx)
}

// GetValidateStatusCertificateScope mocks base method.
func (m *MockMetadataExtendedProvider) GetValidateStatusCertificateScope(ctx context.Context) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetValidateStatusCertificateScope", ctx)
	ret0, _ := ret[0].(bool)
	return ret0
}

// GetValidateStatusCertificateScope indicates an expected call of GetValidateStatusCertificateScope.
func (mr *MockMetadataExtendedProviderMockRecorder) GetValidateStatusCertificateScope(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetValidateStatusCertificateScope", reflect.TypeOf((*MockMetadataExtendedProvider)(nil).GetValidateStatusCertificateScope), ctx)
}

// GetValidateTrustAnchor mocks base method.
func (m *MockMetadataExtendedProvider) GetValidateTrustAnchor(ctx context.Context) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetValidateTrustAnchor", ctx)
	ret0, _ := ret[0].(bool)
	return ret0
}

// GetValidateTrustAnchor indicates an expected call of GetValidateTrustAnchor.
func (mr *MockMetadataExtendedProviderMockRecorder) GetValidateTrustAnchor(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetValidateTrustAnchor", reflect.TypeOf((*MockMetadataExtendedProvider)(nil).GetValidateTrustAnchor), ctx)
}

// GetValidateUserVerification mocks base method.
func (m *MockMetadataExtendedProvider) GetValidateUserVerification(ctx context.Context) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetValidateUserVerification", ctx)
	ret0, _ := ret[0].(bool)
	return ret0
}

// GetValidateUserVerification indicates an expected call of GetValidateUserVerification.
func (mr *MockMetadataExtendedProviderMockRecorder) GetValidateUserVerification(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetValidateUserVerification", reflect.TypeOf((*MockMetadataExtendedProvider)(nil).GetValidateUserVerification), ctx)
}

// ValidateStatusReports mocks base method.
func (m *MockMetadataExtendedProvider) ValidateStatusReports(ctx context.Context, reports []metadata.StatusReport) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateStatusReports", ctx, reports)
	ret0, _ := ret[0].(error)
	return ret0
}

// ValidateStatusReports indicates an expected call of ValidateStatusReports.
func (mr *MockMetadataExtendedProviderMockRecorder) ValidateStatusReports(ctx, reports any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateStatusReports", reflect.TypeOf((*MockMetadataExtendedProvider)(nil).ValidateStatusReports), ctx, reports)
}
